import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma/client.js";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

interface ClinicSeed {
  name: string;
  slug: string;
  address: string;
  barrio: string;
  phone: string;
  email: string | null;
  website: string | null;
  description: string | null;
  imageUrl: string | null;
  hours: Record<string, string | null>;
  specialties: string[];
  animalTypes: string[];
  languages: string[];
  rating: number;
  reviewCount: number;
  price: number;
  isEmergency: boolean;
  lat: number;
  lng: number;
}

const clinics: ClinicSeed[] = [
  // ===== EIXAMPLE (7 clinicas) =====
  {
    name: "Hospital Veterinari Provença",
    slug: "hospital-veterinari-provenca",
    address: "Carrer de Provença, 287",
    barrio: "Eixample",
    phone: "933 215 478",
    email: "info@hvprovenca.cat",
    website: "https://www.hvprovenca.cat",
    description:
      "Hospital veterinari de referència al cor de l'Eixample amb servei d'urgències 24 hores. Disposem de quiròfan, UCI, diagnòstic per imatge avançat i un equip de més de 15 veterinaris especialistes.",
    imageUrl: null,
    hours: {
      monday: "0:00-23:59",
      tuesday: "0:00-23:59",
      wednesday: "0:00-23:59",
      thursday: "0:00-23:59",
      friday: "0:00-23:59",
      saturday: "0:00-23:59",
      sunday: "0:00-23:59",
    },
    specialties: [
      "Urgències 24h",
      "Cirurgia",
      "Traumatologia",
      "Diagnòstic per imatge",
      "UCI",
      "Cardiologia",
    ],
    animalTypes: ["Perros", "Gatos"],
    languages: ["Català", "Castellà", "Anglès"],
    rating: 4.7,
    reviewCount: 312,
    price: 3,
    isEmergency: true,
    lat: 41.394,
    lng: 2.162,
  },
  {
    name: "Clínica Veterinària Eixample",
    slug: "clinica-veterinaria-eixample",
    address: "Carrer d'Aragó, 195",
    barrio: "Eixample",
    phone: "934 531 209",
    email: "cita@veteixample.com",
    website: "https://www.veteixample.com",
    description:
      "Clínica veterinària familiar amb més de 20 anys d'experiència. Atenció personalitzada per a gossos i gats, amb especial dedicació a la dermatologia i l'oftalmologia veterinària.",
    imageUrl: null,
    hours: {
      monday: "9:00-20:00",
      tuesday: "9:00-20:00",
      wednesday: "9:00-20:00",
      thursday: "9:00-20:00",
      friday: "9:00-19:00",
      saturday: "10:00-14:00",
      sunday: null,
    },
    specialties: [
      "Dermatologia",
      "Oftalmologia",
      "Medicina preventiva",
      "Odontologia",
    ],
    animalTypes: ["Perros", "Gatos"],
    languages: ["Català", "Castellà"],
    rating: 4.5,
    reviewCount: 189,
    price: 2,
    isEmergency: false,
    lat: 41.391,
    lng: 2.16,
  },
  {
    name: "Centre Veterinari Balmes",
    slug: "centre-veterinari-balmes",
    address: "Carrer de Balmes, 178",
    barrio: "Eixample",
    phone: "932 174 563",
    email: "balmes@centreveterinari.cat",
    website: "https://www.centreveterinaribalmes.cat",
    description:
      "Centre veterinari modern amb equipament d'última generació. Especialitzats en medicina felina i oncologia veterinària. Sala d'espera separada per a gats.",
    imageUrl: null,
    hours: {
      monday: "9:00-21:00",
      tuesday: "9:00-21:00",
      wednesday: "9:00-21:00",
      thursday: "9:00-21:00",
      friday: "9:00-20:00",
      saturday: "10:00-14:00",
      sunday: null,
    },
    specialties: [
      "Medicina felina",
      "Oncologia",
      "Ecografia",
      "Anàlisis clíniques",
    ],
    animalTypes: ["Perros", "Gatos"],
    languages: ["Català", "Castellà", "Anglès"],
    rating: 4.8,
    reviewCount: 247,
    price: 2,
    isEmergency: false,
    lat: 41.395,
    lng: 2.157,
  },
  {
    name: "Veterinari Casanova",
    slug: "veterinari-casanova",
    address: "Carrer de Casanova, 112",
    barrio: "Eixample",
    phone: "933 098 741",
    email: null,
    website: null,
    description:
      "Consulta veterinària de barri amb tracte proper i preus competitius. El Dr. Ferran Casanova porta atenent animals de l'Eixample des de 1998.",
    imageUrl: null,
    hours: {
      monday: "9:30-13:30",
      tuesday: "9:30-13:30",
      wednesday: "9:30-13:30",
      thursday: "9:30-13:30",
      friday: "9:30-13:30",
      saturday: "10:00-13:00",
      sunday: null,
    },
    specialties: ["Medicina general", "Vacunació", "Cirurgia menor"],
    animalTypes: ["Perros", "Gatos"],
    languages: ["Català", "Castellà"],
    rating: 4.1,
    reviewCount: 87,
    price: 1,
    isEmergency: false,
    lat: 41.389,
    lng: 2.155,
  },
  {
    name: "Exòtics Barcelona",
    slug: "exotics-barcelona",
    address: "Carrer de Girona, 64",
    barrio: "Eixample",
    phone: "931 445 892",
    email: "info@exoticsbarcelona.com",
    website: "https://www.exoticsbarcelona.com",
    description:
      "Centre veterinari especialitzat exclusivament en animals exòtics: aus, rèptils, petits mamífers i amfibis. Laboratori propi i hospitalització amb condicions de temperatura i humitat controlades.",
    imageUrl: null,
    hours: {
      monday: "10:00-19:00",
      tuesday: "10:00-19:00",
      wednesday: "10:00-19:00",
      thursday: "10:00-19:00",
      friday: "10:00-18:00",
      saturday: "10:00-14:00",
      sunday: null,
    },
    specialties: [
      "Animals exòtics",
      "Aves",
      "Reptiles",
      "Petits mamífers",
      "Cirurgia exòtics",
    ],
    animalTypes: ["Aves", "Reptiles", "Conejos", "Exoticos", "Exoticos", "Exoticos"],
    languages: ["Català", "Castellà", "Anglès"],
    rating: 4.6,
    reviewCount: 134,
    price: 2,
    isEmergency: false,
    lat: 41.396,
    lng: 2.168,
  },
  {
    name: "Clínica Veterinària Roger de Llúria",
    slug: "clinica-veterinaria-roger-de-lluria",
    address: "Carrer de Roger de Llúria, 88",
    barrio: "Eixample",
    phone: "934 872 103",
    email: "info@vetroger.cat",
    website: null,
    description:
      "Clínica veterinària amb un equip jove i dinàmic. Serveis de medicina interna, endoscòpia, rehabilitació i fisioteràpia per a animals de companyia.",
    imageUrl: null,
    hours: {
      monday: "9:00-20:00",
      tuesday: "9:00-20:00",
      wednesday: "9:00-20:00",
      thursday: "9:00-20:00",
      friday: "9:00-19:00",
      saturday: "10:00-14:00",
      sunday: null,
    },
    specialties: [
      "Medicina interna",
      "Endoscòpia",
      "Rehabilitació",
      "Fisioteràpia",
    ],
    animalTypes: ["Perros", "Gatos"],
    languages: ["Català", "Castellà"],
    rating: 4.3,
    reviewCount: 156,
    price: 2,
    isEmergency: false,
    lat: 41.393,
    lng: 2.167,
  },
  {
    name: "Vetconsell — Veterinaris Consell de Cent",
    slug: "vetconsell-veterinaris-consell-de-cent",
    address: "Carrer del Consell de Cent, 340",
    barrio: "Eixample",
    phone: "934 159 327",
    email: "hola@vetconsell.cat",
    website: "https://www.vetconsell.cat",
    description:
      "Clínica veterinària integral amb especial atenció a la nutrició i dietètica animal. Servei de peluqueria canina i botiga especialitzada.",
    imageUrl: null,
    hours: {
      monday: "9:00-20:00",
      tuesday: "9:00-20:00",
      wednesday: "9:00-20:00",
      thursday: "9:00-20:00",
      friday: "9:00-19:30",
      saturday: "10:00-14:00",
      sunday: null,
    },
    specialties: [
      "Nutrició i dietètica",
      "Medicina preventiva",
      "Cirurgia general",
      "Peluqueria canina",
    ],
    animalTypes: ["Perros", "Gatos", "Conejos"],
    languages: ["Català", "Castellà", "Anglès"],
    rating: 4.0,
    reviewCount: 98,
    price: 2,
    isEmergency: false,
    lat: 41.39,
    lng: 2.165,
  },

  // ===== GRACIA (5 clinicas) =====
  {
    name: "Centre Veterinari Gràcia",
    slug: "centre-veterinari-gracia",
    address: "Carrer Gran de Gràcia, 157",
    barrio: "Gràcia",
    phone: "932 178 450",
    email: "info@vetgracia.cat",
    website: "https://www.vetgracia.cat",
    description:
      "Referent veterinari al barri de Gràcia des de fa més de 15 anys. Equip de 5 veterinàries amb servei complet de medicina, cirurgia i diagnòstic.",
    imageUrl: null,
    hours: {
      monday: "9:00-20:00",
      tuesday: "9:00-20:00",
      wednesday: "9:00-20:00",
      thursday: "9:00-20:00",
      friday: "9:00-19:00",
      saturday: "10:00-14:00",
      sunday: null,
    },
    specialties: [
      "Medicina general",
      "Cirurgia",
      "Radiografia",
      "Ecografia",
    ],
    animalTypes: ["Perros", "Gatos"],
    languages: ["Català", "Castellà"],
    rating: 4.4,
    reviewCount: 203,
    price: 2,
    isEmergency: false,
    lat: 41.403,
    lng: 2.156,
  },
  {
    name: "Veterinari Verdi",
    slug: "veterinari-verdi",
    address: "Carrer de Verdi, 72",
    barrio: "Gràcia",
    phone: "933 684 215",
    email: "cita@veterinarioverdi.com",
    website: null,
    description:
      "Petita clínica de barri amb un tracte molt proper i familiar. La Dra. Montserrat Puig atén amb passió cada pacient. Especialitat en gats i animals geriàtrics.",
    imageUrl: null,
    hours: {
      monday: "10:00-19:00",
      tuesday: "10:00-19:00",
      wednesday: "10:00-19:00",
      thursday: "10:00-19:00",
      friday: "10:00-18:00",
      saturday: "10:00-13:00",
      sunday: null,
    },
    specialties: [
      "Medicina felina",
      "Geriatria",
      "Medicina preventiva",
    ],
    animalTypes: ["Perros", "Gatos"],
    languages: ["Català", "Castellà"],
    rating: 4.9,
    reviewCount: 167,
    price: 1,
    isEmergency: false,
    lat: 41.405,
    lng: 2.159,
  },
  {
    name: "Clínica Veterinària Torrent",
    slug: "clinica-veterinaria-torrent",
    address: "Carrer del Torrent de l'Olla, 103",
    barrio: "Gràcia",
    phone: "932 456 871",
    email: "torrent@vetstorrent.cat",
    website: "https://www.vetstorrent.cat",
    description:
      "Clínica veterinària amb servei d'etologia i modificació de conducta. Treballem amb gossos i gats amb problemes de comportament, a més d'oferir tots els serveis veterinaris generals.",
    imageUrl: null,
    hours: {
      monday: "9:00-20:00",
      tuesday: "9:00-20:00",
      wednesday: "9:00-20:00",
      thursday: "9:00-20:00",
      friday: "9:00-19:00",
      saturday: "10:00-14:00",
      sunday: null,
    },
    specialties: [
      "Etologia",
      "Modificació de conducta",
      "Medicina general",
      "Cirurgia menor",
    ],
    animalTypes: ["Perros", "Gatos"],
    languages: ["Català", "Castellà", "Anglès"],
    rating: 4.2,
    reviewCount: 112,
    price: 2,
    isEmergency: false,
    lat: 41.402,
    lng: 2.16,
  },
  {
    name: "Fauna Veterinaris",
    slug: "fauna-veterinaris",
    address: "Carrer de l'Astúries, 38",
    barrio: "Gràcia",
    phone: "931 892 047",
    email: "hola@faunavet.cat",
    website: "https://www.faunavet.cat",
    description:
      "Centre veterinari que també atén animals exòtics. Disposem d'instal·lacions adaptades per a rèptils, aus i petits mamífers a més dels serveis habituals per a gossos i gats.",
    imageUrl: null,
    hours: {
      monday: "9:30-20:00",
      tuesday: "9:30-20:00",
      wednesday: "9:30-20:00",
      thursday: "9:30-20:00",
      friday: "9:30-19:00",
      saturday: "10:00-14:00",
      sunday: null,
    },
    specialties: [
      "Animals exòtics",
      "Medicina general",
      "Cirurgia",
      "Dermatologia",
    ],
    animalTypes: [
      "Perros",
      "Gatos",
      "Conejos",
      "Exoticos",
      "Aves",
      "Reptiles",
    ],
    languages: ["Català", "Castellà"],
    rating: 4.3,
    reviewCount: 91,
    price: 2,
    isEmergency: false,
    lat: 41.404,
    lng: 2.155,
  },
  {
    name: "Veterinària Mozart",
    slug: "veterinaria-mozart",
    address: "Carrer de Mozart, 15",
    barrio: "Gràcia",
    phone: "934 159 632",
    email: null,
    website: null,
    description:
      "Consulta veterinària senzilla i econòmica. Vacunació, desparasitació, microxip i consultes generals. Ideal per a revisions rutinàries.",
    imageUrl: null,
    hours: {
      monday: "9:00-14:00",
      tuesday: "9:00-14:00",
      wednesday: "9:00-14:00",
      thursday: "9:00-14:00",
      friday: "9:00-14:00",
      saturday: null,
      sunday: null,
    },
    specialties: ["Medicina preventiva", "Vacunació", "Microxip"],
    animalTypes: ["Perros", "Gatos"],
    languages: ["Català", "Castellà"],
    rating: 3.8,
    reviewCount: 45,
    price: 1,
    isEmergency: false,
    lat: 41.401,
    lng: 2.153,
  },

  // ===== SARRIA-SANT GERVASI (4 clinicas) =====
  {
    name: "Hospital Veterinari Bonanova",
    slug: "hospital-veterinari-bonanova",
    address: "Passeig de la Bonanova, 62",
    barrio: "Sarrià-Sant Gervasi",
    phone: "932 801 245",
    email: "info@hvbonanova.cat",
    website: "https://www.hvbonanova.cat",
    description:
      "Hospital veterinari premium a la zona alta de Barcelona. Instal·lacions de primer nivell amb TAC, ressonància magnètica i servei d'urgències 24 hores. Equip de 12 especialistes.",
    imageUrl: null,
    hours: {
      monday: "0:00-23:59",
      tuesday: "0:00-23:59",
      wednesday: "0:00-23:59",
      thursday: "0:00-23:59",
      friday: "0:00-23:59",
      saturday: "0:00-23:59",
      sunday: "0:00-23:59",
    },
    specialties: [
      "Urgències 24h",
      "Neurologia",
      "TAC",
      "Ressonància magnètica",
      "Cardiologia",
      "Cirurgia avançada",
    ],
    animalTypes: ["Perros", "Gatos"],
    languages: ["Català", "Castellà", "Anglès", "Francès"],
    rating: 4.8,
    reviewCount: 347,
    price: 3,
    isEmergency: true,
    lat: 41.403,
    lng: 2.133,
  },
  {
    name: "Clínica Veterinària Sarrià",
    slug: "clinica-veterinaria-sarria",
    address: "Carrer Major de Sarrià, 94",
    barrio: "Sarrià-Sant Gervasi",
    phone: "932 037 814",
    email: "sarria@clinicavetsarria.com",
    website: "https://www.clinicavetsarria.com",
    description:
      "Clínica veterinària de confiança al cor del barri de Sarrià. Atenció integral amb enfocament en benestar animal i medicina integrativa. Servei d'acupuntura veterinària.",
    imageUrl: null,
    hours: {
      monday: "9:00-20:00",
      tuesday: "9:00-20:00",
      wednesday: "9:00-20:00",
      thursday: "9:00-20:00",
      friday: "9:00-19:00",
      saturday: "10:00-14:00",
      sunday: null,
    },
    specialties: [
      "Medicina integrativa",
      "Acupuntura",
      "Medicina interna",
      "Cirurgia",
    ],
    animalTypes: ["Perros", "Gatos"],
    languages: ["Català", "Castellà", "Anglès"],
    rating: 4.6,
    reviewCount: 178,
    price: 3,
    isEmergency: false,
    lat: 41.399,
    lng: 2.126,
  },
  {
    name: "Centre Veterinari Mandri",
    slug: "centre-veterinari-mandri",
    address: "Carrer de Mandri, 45",
    barrio: "Sarrià-Sant Gervasi",
    phone: "934 178 502",
    email: "mandri@vetermandri.cat",
    website: null,
    description:
      "Centre veterinari amb especial dedicació a la cardiologia i la medicina interna. Ecocardiografia avançada i monitorització Holter per a pacients cardíacs.",
    imageUrl: null,
    hours: {
      monday: "9:00-20:00",
      tuesday: "9:00-20:00",
      wednesday: "9:00-20:00",
      thursday: "9:00-20:00",
      friday: "9:00-19:00",
      saturday: "10:00-14:00",
      sunday: null,
    },
    specialties: [
      "Cardiologia",
      "Ecocardiografia",
      "Medicina interna",
      "Holter",
    ],
    animalTypes: ["Perros", "Gatos"],
    languages: ["Català", "Castellà", "Francès"],
    rating: 4.5,
    reviewCount: 124,
    price: 3,
    isEmergency: false,
    lat: 41.402,
    lng: 2.135,
  },
  {
    name: "Veterinaris Ganduxer",
    slug: "veterinaris-ganduxer",
    address: "Carrer de Ganduxer, 78",
    barrio: "Sarrià-Sant Gervasi",
    phone: "932 098 461",
    email: "ganduxer@vetganduxer.com",
    website: "https://www.vetganduxer.com",
    description:
      "Clínica veterinària elegant i moderna. Especialitzats en odontologia veterinària i dermatologia. Sala d'espera VIP amb wifi i begudes per als propietaris.",
    imageUrl: null,
    hours: {
      monday: "9:00-20:00",
      tuesday: "9:00-20:00",
      wednesday: "9:00-20:00",
      thursday: "9:00-20:00",
      friday: "9:00-19:00",
      saturday: "10:00-14:00",
      sunday: null,
    },
    specialties: [
      "Odontologia",
      "Dermatologia",
      "Cirurgia estètica",
      "Peluqueria",
    ],
    animalTypes: ["Perros", "Gatos"],
    languages: ["Català", "Castellà", "Anglès"],
    rating: 4.2,
    reviewCount: 89,
    price: 3,
    isEmergency: false,
    lat: 41.398,
    lng: 2.13,
  },

  // ===== SANT MARTI (3 clinicas) =====
  {
    name: "Hospital Veterinari Glòries",
    slug: "hospital-veterinari-glories",
    address: "Carrer de Pallars, 212",
    barrio: "Sant Martí",
    phone: "933 562 178",
    email: "urgencies@hvglories.cat",
    website: "https://www.hvglories.cat",
    description:
      "Hospital veterinari amb servei d'urgències 24 hores al districte de Sant Martí. Instal·lacions àmplies amb UCI, quiròfan i sala de diagnòstic per imatge.",
    imageUrl: null,
    hours: {
      monday: "0:00-23:59",
      tuesday: "0:00-23:59",
      wednesday: "0:00-23:59",
      thursday: "0:00-23:59",
      friday: "0:00-23:59",
      saturday: "0:00-23:59",
      sunday: "0:00-23:59",
    },
    specialties: [
      "Urgències 24h",
      "UCI",
      "Cirurgia",
      "Traumatologia",
      "Diagnòstic per imatge",
    ],
    animalTypes: ["Perros", "Gatos"],
    languages: ["Català", "Castellà", "Anglès"],
    rating: 4.4,
    reviewCount: 276,
    price: 2,
    isEmergency: true,
    lat: 41.405,
    lng: 2.193,
  },
  {
    name: "Clínica Veterinària Poblenou",
    slug: "clinica-veterinaria-poblenou",
    address: "Rambla del Poblenou, 89",
    barrio: "Sant Martí",
    phone: "934 851 093",
    email: "hola@vetpoblenou.com",
    website: "https://www.vetpoblenou.com",
    description:
      "Clínica jove i dinàmica al barri del Poblenou. Atenció a gossos, gats i animals exòtics. Servei de telemedicina i consulta online per a seguiments.",
    imageUrl: null,
    hours: {
      monday: "9:00-20:00",
      tuesday: "9:00-20:00",
      wednesday: "9:00-20:00",
      thursday: "9:00-20:00",
      friday: "9:00-19:00",
      saturday: "10:00-14:00",
      sunday: null,
    },
    specialties: [
      "Medicina general",
      "Telemedicina",
      "Animals exòtics",
      "Cirurgia",
    ],
    animalTypes: ["Perros", "Gatos", "Conejos", "Exoticos"],
    languages: ["Català", "Castellà", "Anglès"],
    rating: 4.1,
    reviewCount: 78,
    price: 2,
    isEmergency: false,
    lat: 41.408,
    lng: 2.199,
  },
  {
    name: "Veterinari Pere IV",
    slug: "veterinari-pere-iv",
    address: "Carrer de Pere IV, 168",
    barrio: "Sant Martí",
    phone: "931 765 284",
    email: null,
    website: null,
    description:
      "Veterinari de barri amb preus accessibles. Consulta general, vacunació, desparasitació i cirurgia menor. Bon tracte i molta experiència.",
    imageUrl: null,
    hours: {
      monday: "9:30-19:30",
      tuesday: "9:30-19:30",
      wednesday: "9:30-19:30",
      thursday: "9:30-19:30",
      friday: "9:30-18:30",
      saturday: "10:00-13:00",
      sunday: null,
    },
    specialties: ["Medicina general", "Vacunació", "Cirurgia menor"],
    animalTypes: ["Perros", "Gatos"],
    languages: ["Català", "Castellà"],
    rating: 3.9,
    reviewCount: 52,
    price: 1,
    isEmergency: false,
    lat: 41.409,
    lng: 2.19,
  },

  // ===== SANTS-MONTJUIC (3 clinicas) =====
  {
    name: "Clínica Veterinària Sants",
    slug: "clinica-veterinaria-sants",
    address: "Carrer de Sants, 214",
    barrio: "Sants-Montjuïc",
    phone: "934 312 567",
    email: "info@vetsants.cat",
    website: "https://www.vetsants.cat",
    description:
      "Clínica veterinària de referència al barri de Sants. Equip de 4 veterinàries amb servei complet. Especialitat en traumatologia i rehabilitació postquirúrgica.",
    imageUrl: null,
    hours: {
      monday: "9:00-20:00",
      tuesday: "9:00-20:00",
      wednesday: "9:00-20:00",
      thursday: "9:00-20:00",
      friday: "9:00-19:00",
      saturday: "10:00-14:00",
      sunday: null,
    },
    specialties: [
      "Traumatologia",
      "Rehabilitació",
      "Cirurgia",
      "Radiografia",
    ],
    animalTypes: ["Perros", "Gatos"],
    languages: ["Català", "Castellà"],
    rating: 4.3,
    reviewCount: 165,
    price: 2,
    isEmergency: false,
    lat: 41.377,
    lng: 2.146,
  },
  {
    name: "Veterinari Creu Coberta",
    slug: "veterinari-creu-coberta",
    address: "Carrer de la Creu Coberta, 58",
    barrio: "Sants-Montjuïc",
    phone: "933 891 046",
    email: null,
    website: null,
    description:
      "Consulta veterinària econòmica al cor de Sants. Atenció bàsica per a gossos i gats amb preus molt competitius. Vacunes, xips i revisions generals.",
    imageUrl: null,
    hours: {
      monday: "9:00-19:00",
      tuesday: "9:00-19:00",
      wednesday: "9:00-19:00",
      thursday: "9:00-19:00",
      friday: "9:00-18:00",
      saturday: "10:00-13:00",
      sunday: null,
    },
    specialties: ["Medicina general", "Vacunació", "Microxip"],
    animalTypes: ["Perros", "Gatos"],
    languages: ["Català", "Castellà"],
    rating: 3.6,
    reviewCount: 34,
    price: 1,
    isEmergency: false,
    lat: 41.374,
    lng: 2.144,
  },
  {
    name: "Hospital Veterinari Montjuïc",
    slug: "hospital-veterinari-montjuic",
    address: "Passeig de l'Exposició, 35",
    barrio: "Sants-Montjuïc",
    phone: "934 431 290",
    email: "info@hvmontjuic.com",
    website: "https://www.hvmontjuic.com",
    description:
      "Hospital veterinari amb urgències 24 hores a la zona de Sants-Montjuïc. Servei de cirurgia avançada, endoscòpia i hospitalització. Atenció a animals exòtics.",
    imageUrl: null,
    hours: {
      monday: "0:00-23:59",
      tuesday: "0:00-23:59",
      wednesday: "0:00-23:59",
      thursday: "0:00-23:59",
      friday: "0:00-23:59",
      saturday: "0:00-23:59",
      sunday: "0:00-23:59",
    },
    specialties: [
      "Urgències 24h",
      "Endoscòpia",
      "Cirurgia avançada",
      "Hospitalització",
    ],
    animalTypes: ["Perros", "Gatos", "Conejos", "Aves"],
    languages: ["Català", "Castellà", "Anglès"],
    rating: 4.5,
    reviewCount: 198,
    price: 2,
    isEmergency: true,
    lat: 41.375,
    lng: 2.152,
  },

  // ===== HORTA-GUINARDO (2 clinicas) =====
  {
    name: "Centre Veterinari Guinardó",
    slug: "centre-veterinari-guinardo",
    address: "Ronda del Guinardó, 112",
    barrio: "Horta-Guinardó",
    phone: "934 502 831",
    email: "guinardo@vetguinardo.cat",
    website: "https://www.vetguinardo.cat",
    description:
      "Centre veterinari familiar al barri del Guinardó. Atenció personalitzada amb horaris amplis. Servei de laboratori propi per a anàlisis ràpides.",
    imageUrl: null,
    hours: {
      monday: "9:00-20:00",
      tuesday: "9:00-20:00",
      wednesday: "9:00-20:00",
      thursday: "9:00-20:00",
      friday: "9:00-19:00",
      saturday: "10:00-14:00",
      sunday: null,
    },
    specialties: [
      "Medicina general",
      "Laboratori",
      "Ecografia",
      "Cirurgia",
    ],
    animalTypes: ["Perros", "Gatos"],
    languages: ["Català", "Castellà"],
    rating: 4.0,
    reviewCount: 76,
    price: 1,
    isEmergency: false,
    lat: 41.421,
    lng: 2.17,
  },
  {
    name: "Clínica Veterinària Horta",
    slug: "clinica-veterinaria-horta",
    address: "Carrer del Dante, 47",
    barrio: "Horta-Guinardó",
    phone: "933 578 194",
    email: "horta@vethorta.com",
    website: null,
    description:
      "Clínica veterinària amb més de 25 anys al barri d'Horta. Servei de medicina general i cirurgia. Atenció especial a gossos de races grans i geriatria canina.",
    imageUrl: null,
    hours: {
      monday: "9:00-19:30",
      tuesday: "9:00-19:30",
      wednesday: "9:00-19:30",
      thursday: "9:00-19:30",
      friday: "9:00-18:30",
      saturday: "10:00-13:00",
      sunday: null,
    },
    specialties: ["Geriatria canina", "Medicina general", "Cirurgia"],
    animalTypes: ["Perros", "Gatos"],
    languages: ["Català", "Castellà"],
    rating: 4.1,
    reviewCount: 63,
    price: 1,
    isEmergency: false,
    lat: 41.423,
    lng: 2.165,
  },

  // ===== LES CORTS (2 clinicas) =====
  {
    name: "Clínica Veterinària Les Corts",
    slug: "clinica-veterinaria-les-corts",
    address: "Travessera de Les Corts, 185",
    barrio: "Les Corts",
    phone: "934 901 267",
    email: "info@vetlescorts.cat",
    website: "https://www.vetlescorts.cat",
    description:
      "Clínica veterinària completa al districte de Les Corts. Equip de 3 veterinaris amb especialitats en oncologia i cirurgia de teixits tous.",
    imageUrl: null,
    hours: {
      monday: "9:00-20:00",
      tuesday: "9:00-20:00",
      wednesday: "9:00-20:00",
      thursday: "9:00-20:00",
      friday: "9:00-19:00",
      saturday: "10:00-14:00",
      sunday: null,
    },
    specialties: [
      "Oncologia",
      "Cirurgia teixits tous",
      "Medicina interna",
      "Ecografia",
    ],
    animalTypes: ["Perros", "Gatos"],
    languages: ["Català", "Castellà", "Anglès"],
    rating: 4.4,
    reviewCount: 143,
    price: 2,
    isEmergency: false,
    lat: 41.386,
    lng: 2.134,
  },
  {
    name: "Veterinari Numància",
    slug: "veterinari-numancia",
    address: "Carrer de Numància, 53",
    barrio: "Les Corts",
    phone: "934 050 982",
    email: "numancia@vetnumancia.com",
    website: null,
    description:
      "Veterinari de barri amb tracte molt proper. Servei integral per a gossos, gats i exòtics. Bona relació qualitat-preu.",
    imageUrl: null,
    hours: {
      monday: "9:30-20:00",
      tuesday: "9:30-20:00",
      wednesday: "9:30-20:00",
      thursday: "9:30-20:00",
      friday: "9:30-19:00",
      saturday: "10:00-14:00",
      sunday: null,
    },
    specialties: [
      "Medicina general",
      "Animals exòtics",
      "Vacunació",
      "Cirurgia menor",
    ],
    animalTypes: ["Perros", "Gatos", "Conejos", "Exoticos", "Exoticos"],
    languages: ["Català", "Castellà"],
    rating: 3.7,
    reviewCount: 42,
    price: 2,
    isEmergency: false,
    lat: 41.385,
    lng: 2.128,
  },

  // ===== NOU BARRIS (1 clinica) =====
  {
    name: "Clínica Veterinària Nou Barris",
    slug: "clinica-veterinaria-nou-barris",
    address: "Via Júlia, 157",
    barrio: "Nou Barris",
    phone: "933 502 174",
    email: "info@vetnoubarris.cat",
    website: null,
    description:
      "Clínica veterinària de barri amb preus molt assequibles. Atenció completa per a gossos i gats. Campanyes de vacunació i esterilització a preus reduïts.",
    imageUrl: null,
    hours: {
      monday: "9:00-19:00",
      tuesday: "9:00-19:00",
      wednesday: "9:00-19:00",
      thursday: "9:00-19:00",
      friday: "9:00-18:00",
      saturday: "10:00-13:00",
      sunday: null,
    },
    specialties: [
      "Medicina general",
      "Vacunació",
      "Esterilització",
      "Microxip",
    ],
    animalTypes: ["Perros", "Gatos"],
    languages: ["Català", "Castellà"],
    rating: 3.2,
    reviewCount: 28,
    price: 1,
    isEmergency: false,
    lat: 41.442,
    lng: 2.178,
  },

  // ===== SANT ANDREU (1 clinica) =====
  {
    name: "Hospital Veterinari Sant Andreu",
    slug: "hospital-veterinari-sant-andreu",
    address: "Gran de Sant Andreu, 282",
    barrio: "Sant Andreu",
    phone: "933 459 801",
    email: "santandreu@hvsantandreu.cat",
    website: "https://www.hvsantandreu.cat",
    description:
      "Hospital veterinari històric de Sant Andreu, obert des de 1985. Un dels centres amb més tradició del districte, amb servei complet de medicina, cirurgia i diagnòstic per imatge.",
    imageUrl: null,
    hours: {
      monday: "9:00-20:00",
      tuesday: "9:00-20:00",
      wednesday: "9:00-20:00",
      thursday: "9:00-20:00",
      friday: "9:00-19:00",
      saturday: "10:00-14:00",
      sunday: null,
    },
    specialties: [
      "Medicina general",
      "Cirurgia",
      "Radiografia",
      "Diagnòstic per imatge",
    ],
    animalTypes: ["Perros", "Gatos"],
    languages: ["Català", "Castellà"],
    rating: 4.0,
    reviewCount: 112,
    price: 1,
    isEmergency: false,
    lat: 41.436,
    lng: 2.19,
  },
];

async function main() {
  console.log("Seeding VetBCN database with 28 clinics...");

  // Clear existing data
  await prisma.clinic.deleteMany();
  console.log("Cleared existing clinic data.");

  for (const clinic of clinics) {
    await prisma.clinic.create({
      data: clinic,
    });
    console.log(`  Created: ${clinic.name}`);
  }

  console.log(`\nSeeding complete! ${clinics.length} clinics created.`);

  // Summary stats
  const byBarrio = clinics.reduce(
    (acc, c) => {
      acc[c.barrio] = (acc[c.barrio] || 0) + 1;
      return acc;
    },
    {} as Record<string, number>
  );
  console.log("\nDistribution by barrio:");
  Object.entries(byBarrio)
    .sort((a, b) => b[1] - a[1])
    .forEach(([barrio, count]) => console.log(`  ${barrio}: ${count}`));

  const emergencyCount = clinics.filter((c) => c.isEmergency).length;
  console.log(`\nEmergency 24h: ${emergencyCount} clinics`);

  const priceDistribution = clinics.reduce(
    (acc, c) => {
      const label = c.price === 1 ? "€" : c.price === 2 ? "€€" : "€€€";
      acc[label] = (acc[label] || 0) + 1;
      return acc;
    },
    {} as Record<string, number>
  );
  console.log("Price distribution:");
  Object.entries(priceDistribution).forEach(([price, count]) =>
    console.log(`  ${price}: ${count}`)
  );
}

main()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e);
    prisma.$disconnect();
    process.exit(1);
  });
